const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../domain');
const actor={id:'admin',name:'Teste'};
function fixture(){const s=D.seed();s.payments=[];s.audit=[];s.tasks=[];s.contacts=[{id:'c',name:'Pessoa Teste',email:'teste@exemplo.com',phone:'',document:'',type:'PF',origin:'Site',funnel:'Inbound',stage:0,history:[],owner:'admin'}];return s}
test('Contato, duplicidade e documento',()=>{const s=fixture();assert.throws(()=>D.validateContact({...s.contacts[0],email:'',phone:''},s.contacts));assert.throws(()=>D.validateContact({...s.contacts[0],id:'new'},s.contacts));assert.equal(D.documentValid('529.982.247-25','PF'),true);assert.equal(D.documentValid('11.222.333/0001-81','PJ'),true);assert.equal(D.documentValid('111.111.111-11','PF'),false);assert.equal(D.documentValid('12.345.678/0001-00','PJ'),false)});
test('Movimentacao preserva sequencia, data e operador',()=>{const s=fixture();D.move(s,actor,'c',1,'Interesse');D.move(s,actor,'c',2,'Conheceu a causa');D.move(s,actor,'c',0,'Retomada');assert.equal(s.contacts[0].history.length,3);assert.equal(s.contacts[0].stage,0);assert.equal(s.audit[0].actor,'admin');assert.ok(s.audit[0].at)});
test('Conversao e pagamento parcial quitam competencia sem duplicar Pix',()=>{const s=fixture();D.convert(s,actor,'c',{mode:'Recorrente',amount:100,due:10});const d={contactId:'c',amount:40,date:D.today(),period:D.month(),pix:'PIX-1',destination:'Obras sociais'};const p=D.payment(s,actor,d);assert.equal(D.pending(s)[0].amount,60);assert.ok(p.receipt);assert.equal(p.actor,'admin');assert.throws(()=>D.payment(s,actor,d));D.payment(s,actor,{...d,amount:60,pix:'PIX-2'});assert.equal(D.pending(s).length,0);assert.equal(s.payments.reduce((n,p)=>n+p.amount,0),100);assert.throws(()=>D.payment(s,actor,{...d,amount:'roupas',pix:'PIX-3'}))});
test('Dois meses sem pagamento acionam inadimplencia uma vez',()=>{const s=fixture();s.contacts[0].plan={mode:'Recorrente',amount:100,due:10,since:'2026-07',status:'Ativo'};D.reconcile(s,actor,new Date('2026-10-02T12:00:00'));assert.equal(s.contacts[0].plan.status,'Inadimplente');assert.equal(s.tasks.length,1);D.reconcile(s,actor,new Date('2026-10-02T12:00:00'));assert.equal(s.tasks.length,1)});
test('CSV descarta invalidos e duplicidades inclusive dentro do arquivo',()=>{const s=fixture(),l={id:'l',name:'Lista',contacts:[],imports:[]};const r=D.importRows(s,actor,l,D.parseCSV('nome;email;telefone\n"Ana; Maria";ana@exemplo.com;86999990000\nRepetido;ana@exemplo.com;\nInvalido;sem-email;\nExiste;teste@exemplo.com;'));assert.equal(r.imported,1);assert.equal(r.duplicates,2);assert.equal(r.invalid,1);assert.equal(l.contacts.length,1);assert.equal(s.contacts[0].name,'Ana; Maria')});
test('Descadastro bloqueia envio e historico acompanha destinatarios',()=>{const s=fixture();s.contacts.push({...s.contacts[0],id:'blocked',email:'bloqueado@exemplo.com',optOut:true,history:[]});const n=D.send(s,actor,['c','blocked','c'],'Ola','Mensagem');assert.equal(n,1);assert.equal(s.campaigns[0].contacts.length,1);assert.equal(s.contacts[1].history.length,0);assert.throws(()=>D.send(s,actor,['blocked'],'Ola','Mensagem'))});
test('Semente tem pagamentos vinculados, monetarios e auditaveis',()=>{const s=D.seed();assert.equal(s.contacts.length,24);assert.ok(s.payments.length);for(const p of s.payments){assert.ok(s.contacts.find(c=>c.id===p.contactId)?.plan);assert.equal(typeof p.amount,'number');assert.ok(p.amount>0);assert.ok(p.actor&&p.at&&p.receipt)}});
